version: 0.9.{build}
skip_tags: true
skip_commits:
  message: /\[chore\]/
only_commits:
  files:
    - '**/*.h'
    - '**/*.hpp'
    - '**/*.cpp'
    - '**/*.sln'
    - '**/*.vcxproj'
    - '**/*.rc'
configuration:
- Debug
- Release
platform:
- Win32
before_build:
- ps: nuget restore
build:
  project: ./Kiwano.sln
  parallel: true
  verbosity: minimal
notifications:
- provider: Email
  to:
  - 569629550@qq.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false