version: 0.9.{build}

skip_tags: true

image:
- Visual Studio 2019
- Visual Studio 2017
- Visual Studio 2015

skip_commits:
  message: /\[chore\]/

only_commits:
  files:
    - '**/*.h'
    - '**/*.hpp'
    - '**/*.cpp'
    - '**/*.sln'
    - '**/*.vcxproj'
    - '**/*.rc'

configuration:
- Debug
- Release

platform:
- Win32

before_build:
- ps: nuget restore projects/Kiwano.sln

build:
  parallel: true
  project: projects/Kiwano.sln
  verbosity: normal

artifacts:
- path: projects/output/
  name: $(platform).$(configuration)
  type: zip

notifications:
- provider: Email
  to:
  - 569629550@qq.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false