name: Deploy to Tencent Cloud COS

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: build
      uses: mattnotmitt/doxygen-action@v1.9.4

    - name: Upload
      uses: zkqiang/tencent-cos-action@v0.1.0
      with:
        args: upload -rf --sync -y ./docs/html/ /
        secret_id: ${{ secrets.QCLOUD_SECRET_ID }}
        secret_key: ${{ secrets.QCLOUD_SECRET_KEY }}
        bucket: kiwano-web-1252696634
        region: ap-guangzhou
